# Generated by Django 6.0.2 on 2026-03-02 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_doctorprofile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='phone_number',
        ),
    ]
