# Generated by Django 4.2.19 on 2026-03-25 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_patient_creator_alter_assessment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='creator',
        ),
    ]
