# Generated by Django 4.2.19 on 2026-03-27 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_patient_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
